#!/bin/sh
### BEGIN INIT INFO
# Provides:          ledpad
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Start ledpad driver and application.
# Description:
### END INIT INFO
#
# (c) 2022 Yunjae Lim <launius@gmail.com>
#

case "$1" in
	start)
		echo -n "Starting ledpad application: "
		insmod /lib/modules/5.10.17-rt32-yocto-preempt-rt/kernel/drivers/leds/leds-ledpad.ko
		start-stop-daemon --start --exec  /usr/bin/ledpad &
		echo "done"
		;;

	stop)
		echo -n "Stopping ledpad application"
		start-stop-daemon --stop --exec  /usr/bin/ledpad
		rmmod /lib/modules/5.10.17-rt32-yocto-preempt-rt/kernel/drivers/leds/leds-ledpad.ko
		echo "done"
		;;

	restart)
		$0 stop
		$0 start
		;;

	*)
		echo "Usage: ledpad_service { start | stop | restart }" >&2
		exit 1
		;;
esac

exit 0
